In [56]:
# Imports
import pandas as pd
import numpy as np
import json as json
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [57]:
 # Loading the data from CSV into panadas dataframe
tempIncomeStatement = pd.read_csv (r'../data/income_statement.csv', sep=',')
tempCashFlow = pd.read_csv (r'../data/cash_flow.csv', sep=',')
tempBalanceSheet = pd.read_csv (r'../data/balance-sheet.csv', sep=',')
tempEarnings = pd.read_csv (r'../data/EARNINGS.csv', sep=',')

tempMonthly = pd.read_csv (r'../data/monthly-data.csv', sep=',')
TickerSymbols = pd.read_csv (r'../data/nasdaq_screener_sorted_values.csv', sep=',')

In [58]:
# Printing Income statement
print(tempIncomeStatement)
print(tempIncomeStatement.columns)

# Printing Cash Flow
print(tempCashFlow.shape)
print(tempCashFlow.columns)

# Printing Balance Sheet
print(tempBalanceSheet.shape)
print(tempBalanceSheet.columns)

# Printing Earnings
print(tempEarnings.shape)
print(tempEarnings.columns)

     fiscalDateEnding reportedCurrency  grossProfit  totalRevenue  \
0          2021-09-30              USD  35174000000   82688000000
1          2021-06-30              USD  35255000000   80769000000
2          2021-03-31              USD  38079000000   88914000000
3          2020-12-31              USD  44328000000  110801000000
4          2020-09-30              USD  24689000000   64698000000
...               ...              ...          ...           ...
3899       2017-05-31              USD    345500000     572700000
3900       2017-02-28              USD    325900000     566400000
3901       2016-11-30              USD    356900000     623700000
3902       2016-08-31              USD    326900000     597300000
3903       2016-05-31              USD    248800000     710500000

     costOfRevenue costofGoodsAndServicesSold operatingIncome  \
0      53802000000                48186000000     23786000000
1      51591000000                46179000000     24126000000
2      56819000000                51505000000     27503000000
3      72742000000                67111000000     33534000000
4      44945000000                40009000000     14775000000
...            ...                        ...             ...
3899     227200000                  227200000       101400000
3900     240400000                  240400000         1000000
3901     266800000                  266800000        93200000
3902     270400000                  270400000        50400000
3903     461700000                  461700000      -773200000

     sellingGeneralAndAdministrative researchAndDevelopment operatingExpenses  \
0                         5616000000             5772000000       11388000000
1                         5412000000             5717000000       11129000000
2                         5314000000             5262000000       10576000000
3                         5631000000             5163000000       10794000000
4                         4936000000             4978000000        9914000000
...                              ...                    ...               ...
3899                        55200000              188600000         244100000
3900                        36505000              176700000         324900000
3901                        29524000              202200000         263600000
3902                        36833000              208200000         276600000
3903                        35259000              286100000        1022000000

      ... depreciationAndAmortization incomeBeforeTax incomeTaxExpense  \
0     ...                  2989000000     23248000000       2697000000
1     ...                  2832000000     24369000000       2625000000
2     ...                  2797000000     28011000000       4381000000
3     ...                  2666000000     33579000000       4824000000
4     ...                  2702000000     14901000000       2228000000
...   ...                         ...             ...              ...
3899  ...                    21800000       104800000          5200000
3900  ...                    28600000         4800000         68300000
3901  ...                    30000000        98700000         15500000
3902  ...                    29900000        56600000         -5800000
3903  ...                    28200000      -766400000          5500000

     interestAndDebtExpense netIncomeFromContinuingOperations  \
0                 672000000                       20551000000
1                 665000000                       21744000000
2                 670000000                       23630000000
3                 638000000                       28755000000
4                 634000000                       24689000000
...                     ...                               ...
3899                   None                         135450000
3900                   None                          96970000
3901                   None                         -57248000
3902                   None                          72616000
3903                   None                          51305000

     comprehensiveIncomeNetOfTax         ebit       ebitda    netIncome symbol
0                    20656000000  23920000000  26909000000  20551000000   AAPL
1                    22088000000  25034000000  27866000000  21744000000   AAPL
2                    23165000000  28681000000  31478000000  23630000000   AAPL
3                    29340000000  34217000000  36883000000  28755000000   AAPL
4                    12817000000  15535000000  18237000000  12673000000   AAPL
...                          ...          ...          ...          ...    ...
3899                        None    111851000    133651000    106600000   MRVL
3900                        None    -11800000     16800000    -80100000   MRVL
3901                        None     88100000    118100000     72600000   MRVL
3902                        None     45597000     75497000     51300000   MRVL
3903                        None   -766400000   -738200000   -771900000   MRVL

[3904 rows x 27 columns]
Index(['fiscalDateEnding', 'reportedCurrency', 'grossProfit', 'totalRevenue',
       'costOfRevenue', 'costofGoodsAndServicesSold', 'operatingIncome',
       'sellingGeneralAndAdministrative', 'researchAndDevelopment',
       'operatingExpenses', 'investmentIncomeNet', 'netInterestIncome',
       'interestIncome', 'interestExpense', 'nonInterestIncome',
       'otherNonOperatingIncome', 'depreciation',
       'depreciationAndAmortization', 'incomeBeforeTax', 'incomeTaxExpense',
       'interestAndDebtExpense', 'netIncomeFromContinuingOperations',
       'comprehensiveIncomeNetOfTax', 'ebit', 'ebitda', 'netIncome', 'symbol'],
      dtype='object')
(3885, 30)
Index(['fiscalDateEnding', 'reportedCurrency', 'operatingCashflow',
       'paymentsForOperatingActivities', 'proceedsFromOperatingActivities',
       'changeInOperatingLiabilities', 'changeInOperatingAssets',
       'depreciationDepletionAndAmortization', 'capitalExpenditures',
       'changeInReceivables', 'changeInInventory', 'profitLoss',
       'cashflowFromInvestment', 'cashflowFromFinancing',
       'proceedsFromRepaymentsOfShortTermDebt',
       'paymentsForRepurchaseOfCommonStock', 'paymentsForRepurchaseOfEquity',
       'paymentsForRepurchaseOfPreferredStock', 'dividendPayout',
       'dividendPayoutCommonStock', 'dividendPayoutPreferredStock',
       'proceedsFromIssuanceOfCommonStock',
       'proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet',
       'proceedsFromIssuanceOfPreferredStock',
       'proceedsFromRepurchaseOfEquity', 'proceedsFromSaleOfTreasuryStock',
       'changeInCashAndCashEquivalents', 'changeInExchangeRate', 'netIncome',
       'symbol'],
      dtype='object')
(3857, 39)
Index(['fiscalDateEnding', 'reportedCurrency', 'totalAssets',
       'totalCurrentAssets', 'cashAndCashEquivalentsAtCarryingValue',
       'cashAndShortTermInvestments', 'inventory', 'currentNetReceivables',
       'totalNonCurrentAssets', 'propertyPlantEquipment',
       'accumulatedDepreciationAmortizationPPE', 'intangibleAssets',
       'intangibleAssetsExcludingGoodwill', 'goodwill', 'investments',
       'longTermInvestments', 'shortTermInvestments', 'otherCurrentAssets',
       'otherNonCurrrentAssets', 'totalLiabilities', 'totalCurrentLiabilities',
       'currentAccountsPayable', 'deferredRevenue', 'currentDebt',
       'shortTermDebt', 'totalNonCurrentLiabilities',
       'capitalLeaseObligations', 'longTermDebt', 'currentLongTermDebt',
       'longTermDebtNoncurrent', 'shortLongTermDebtTotal',
       'otherCurrentLiabilities', 'otherNonCurrentLiabilities',
       'totalShareholderEquity', 'treasuryStock', 'retainedEarnings',
       'commonStock', 'commonStockSharesOutstanding', 'symbol'],
      dtype='object')
(15813, 7)
Index(['fiscalDateEnding', 'reportedDate', 'reportedEPS', 'estimatedEPS',
       'surprise', 'surprisePercentage', 'symbol'],
      dtype='object')

In [61]:
# renaming Balance sheet column "fiscalDateEnding" to "timestamp" to match column name on both dataframes
tempIncomeStatement = tempIncomeStatement.rename(columns={"fiscalDateEnding": "timestamp"})
tempCashFlow = tempCashFlow.rename(columns={"fiscalDateEnding": "timestamp"})
tempBalanceSheet = tempBalanceSheet.rename(columns={"fiscalDateEnding": "timestamp"})
tempEarnings = tempEarnings.rename(columns={"fiscalDateEnding": "timestamp"})

# Merging all 4 frames into one

# Daily dates does not overlap on both dataframes, CompanyMonthly has the last trading day (not including weekends)
# While CompanyBalanaceSheet always has the last day of the month (including weekends)
# We need to cut out the daily date for both dataframes["timestamp"], to be able to merge them properly.
# Slicing the timestamp in CompanyMonthly, removing the days
sliceMonthly = tempMonthly["timestamp"].str.slice(0, -3)
tempMonthly["timestamp"] = sliceMonthly

# Printing
print("Monthly Data:")
print(tempMonthly["timestamp"])

# Slicing the timestamp in Income Statement, removing the days
sliceIncomestatement = tempIncomeStatement["timestamp"].str.slice(0, -3)
# For some reason i needed to use Iloc here, don't know why... 
tempIncomeStatement["timestamp"] = sliceIncomestatement

# Slicing the timestamp in Cash Flow, removing the days
sliceCashFlow = tempCashFlow["timestamp"].str.slice(0, -3)
# For some reason i needed to use Iloc here, don't know why... 
tempCashFlow["timestamp"] = sliceCashFlow

# Slicing the timestamp in CompanyBalanceSheet, removing the days
sliceBalanceSheet = tempBalanceSheet["timestamp"].str.slice(0, -3)
# For some reason i needed to use Iloc here, don't know why... 
tempBalanceSheet["timestamp"] = sliceBalanceSheet

# Slicing the timestamp in Earnings, removing the days
sliceEarnings = tempEarnings["timestamp"].str.slice(0, -3)
# For some reason i needed to use Iloc here, don't know why... 
tempEarnings["timestamp"] = sliceEarnings

# Printing
print("Income Statement:")
print(tempIncomeStatement["timestamp"])
print("Cash Flow:")
print(tempCashFlow["timestamp"])
print("Balance Sheet:")
print(tempBalanceSheet["timestamp"])
print("Earnings:")
print(tempEarnings["timestamp"])
print("Ticker Symbols:")
print(TickerSymbols["Symbol"])

Monthly Data:
0        2021
1        2021
2        2021
3        2021
4        2021
         ...
43662    2000
43663    2000
43664    2000
43665    2000
43666    2000
Name: timestamp, Length: 43667, dtype: object
Income Statement:
0       2021
1       2021
2       2021
3       2020
4       2020
        ...
3899    2017
3900    2017
3901    2016
3902    2016
3903    2016
Name: timestamp, Length: 3904, dtype: object
Cash Flow:
0       2021
1       2021
2       2021
3       2020
4       2020
        ...
3880    2017
3881    2017
3882    2016
3883    2016
3884    2016
Name: timestamp, Length: 3885, dtype: object
Balance Sheet:
0       2021
1       2021
2       2021
3       2020
4       2020
        ...
3852    2017
3853    2017
3854    2016
3855    2016
3856    2016
Name: timestamp, Length: 3857, dtype: object
Earnings:
0        2021
1        2021
2        2021
3        2020
4        2020
         ...
15808    2001
15809    2001
15810    2000
15811    2000
15812    2000
Name: timestamp, Length: 15813, dtype: object
Ticker Symbols:
0       AAPL
1       MSFT
2       GOOG
3      GOOGL
4       AMZN
       ...
195     STLA
196      NIO
197      UBS
198     CRWD
199     MRVL
Name: Symbol, Length: 199, dtype: object

In [62]:
# for each company we want to make adjustments needed for each companys features and then we will merge them into one df

#------------ add error if ticker symbol is not in TickerSymbols["Symbol"] or size < 200


TickerSymbols = TickerSymbols[~TickerSymbols['Symbol'].isin(['RIVN'])]
final_df = pd.DataFrame()
counter = 0

for tickerSymbol in TickerSymbols["Symbol"]:
    counter = counter +1
    print("this is the beginning of the forloop, tickersymbol: " + tickerSymbol + "counter = " + str(counter))
    
    # filter all dataframes for each ticketsymbol (stock)
    CompanyIncomeStatement = tempIncomeStatement.loc[tempIncomeStatement["symbol"] == tickerSymbol]
    CompanyCashFlow = tempCashFlow.loc[tempCashFlow["symbol"] == tickerSymbol]
    CompanyBalanceSheet = tempBalanceSheet.loc[tempBalanceSheet["symbol"] == tickerSymbol]
    CompanyEarnings = tempEarnings.loc[tempEarnings["symbol"] == tickerSymbol]
    CompanyMonthly = tempMonthly.loc[tempMonthly["Symbol"] == tickerSymbol]
    
    # Removing symbol for all Company dataframes
    CompanyIncomeStatement.drop(["reportedCurrency", 'symbol'], axis=1, inplace=True)
    CompanyCashFlow.drop(["reportedCurrency", 'symbol'], axis=1, inplace=True)
    CompanyBalanceSheet.drop(["reportedCurrency", 'symbol'], axis=1, inplace=True)
    CompanyEarnings.drop(['symbol'], axis=1, inplace=True)
    CompanyMonthly.drop(['Symbol'], axis=1, inplace=True)
    
    # Cutting out unecessary data from the CompanyMonthly
    # We only need price data in CompanyMonthly within the daterange of the 20 rows on CompanyBalanceSheet data
    # every row is 3 months in CompanyBalanceSheet. Every row in CompanyMonthly is 1 month, 3x20 = 60.
    idx = (CompanyMonthly.index[0]+60)
    CompanyMonthly = CompanyMonthly.loc[:idx]

    # calculating 1 month labels
    CompanyMonthly["1m"] = CompanyMonthly["close"].pct_change(periods = -1).shift(periods = 1)
    #print(CompanyMonthly.head(21))
    
    # merge all df into a temp df
    temp_df = pd.merge(CompanyIncomeStatement, CompanyCashFlow, how="outer", on = "timestamp")
    temp_df = pd.merge(temp_df, CompanyBalanceSheet, how="outer", on = "timestamp")
    temp_df = pd.merge(temp_df, CompanyEarnings, how="outer", on = "timestamp")
    print(temp_df)
    # merging the rows from balance sheet and monthly on timestamp.
    merged_df = pd.merge(temp_df, CompanyMonthly, how="outer", on = "timestamp")
    
    # removing the rows over 20
    merged_df = merged_df.loc[:19]

    # calculate how much the increase is in percentage, interval of 3 months
    # also offsetting by 1, to get the labels on the correct row.
    cat = ["timestamp", "symbol", "close", "change"]
    merged_df["3m"] = merged_df["close"].pct_change(periods = -1).shift(periods = 1)
    
    # Removing the first row, because we do not have a label for it, 3 months have not passed yet for us to get the end price of the 3 month cycle
    #merged_df.drop(index=merged_df.index[0], axis=0, inplace=True)

    # Also dropping columns that we do not need, symbol, Symbol, open, high, low, close, volume etc.
    merged_df.drop(['open','high','low','volume', "close", "timestamp",], axis=1, inplace=True)

    # replacing all "None" strings with NaN data type
    merged_df = merged_df.replace('None', np.nan)

    # Checking for "None" Strings
    sub_df = merged_df.loc[: , (merged_df == 'None').any()]

    # Checking for "None" Strings
    sub_df = merged_df.loc[: , (merged_df == 'None').any()]
    print(sub_df)
    
    for col in merged_df.columns:
        if col != "timestamp":
            merged_df[col] = merged_df[col].astype("float")
            merged_df[col] = merged_df[col].replace(np.nan, merged_df[col].mean())
    
    # adding it to the final dataframe
    final_df = pd.concat([final_df, merged_df], axis=0)

this is the beginning of the forloop, tickersymbol: AAPLcounter = 1
     timestamp  grossProfit totalRevenue costOfRevenue  \
0         2021  35174000000  82688000000   53802000000
1         2021  35174000000  82688000000   53802000000
2         2021  35174000000  82688000000   53802000000
3         2021  35174000000  82688000000   53802000000
4         2021  35174000000  82688000000   53802000000
...        ...          ...          ...           ...
1184      1997          NaN          NaN           NaN
1185      1996          NaN          NaN           NaN
1186      1996          NaN          NaN           NaN
1187      1996          NaN          NaN           NaN
1188      1996          NaN          NaN           NaN

     costofGoodsAndServicesSold operatingIncome  \
0                   48186000000     23786000000
1                   48186000000     23786000000
2                   48186000000     23786000000
3                   48186000000     23786000000
4                   48186000000     23786000000
...                         ...             ...
1184                        NaN             NaN
1185                        NaN             NaN
1186                        NaN             NaN
1187                        NaN             NaN
1188                        NaN             NaN

     sellingGeneralAndAdministrative researchAndDevelopment operatingExpenses  \
0                         5616000000             5772000000       11388000000
1                         5616000000             5772000000       11388000000
2                         5616000000             5772000000       11388000000
3                         5616000000             5772000000       11388000000
4                         5616000000             5772000000       11388000000
...                              ...                    ...               ...
1184                             NaN                    NaN               NaN
1185                             NaN                    NaN               NaN
1186                             NaN                    NaN               NaN
1187                             NaN                    NaN               NaN
1188                             NaN                    NaN               NaN

     investmentIncomeNet  ... totalShareholderEquity treasuryStock  \
0              659000000  ...            63090000000          None
1              659000000  ...            63090000000          None
2              659000000  ...            63090000000          None
3              659000000  ...            64280000000          None
4              659000000  ...            64280000000          None
...                  ...  ...                    ...           ...
1184                 NaN  ...                    NaN           NaN
1185                 NaN  ...                    NaN           NaN
1186                 NaN  ...                    NaN           NaN
1187                 NaN  ...                    NaN           NaN
1188                 NaN  ...                    NaN           NaN

     retainedEarnings  commonStock commonStockSharesOutstanding reportedDate  \
0          5562000000  57365000000                  16426786000   2021-10-28
1          5562000000  57365000000                  16426786000   2021-07-27
2          5562000000  57365000000                  16426786000   2021-04-28
3          9233000000  54989000000                  16556942000   2021-10-28
4          9233000000  54989000000                  16556942000   2021-07-27
...               ...          ...                          ...          ...
1184              NaN          NaN                          NaN   1997-04-16
1185              NaN          NaN                          NaN   1997-01-15
1186              NaN          NaN                          NaN   1996-10-16
1187              NaN          NaN                          NaN   1996-07-17
1188              NaN          NaN                          NaN   1996-04-17

     reportedEPS estimatedEPS surprise surprisePercentage
0           1.24        1.238    0.002             0.1616
1            1.3       1.0143   0.2857            28.1672
2            1.4       0.9888   0.4112            41.5858
3           1.24        1.238    0.002             0.1616
4            1.3       1.0143   0.2857            28.1672
...          ...          ...      ...                ...
1184       -0.05        -0.04    -0.01                -25
1185       -0.03        -0.02    -0.01                -50
1186      0.0018        -0.01   0.0118                118
1187       -0.02        -0.04     0.02                 50
1188       -0.07        -0.05    -0.02                -40

[1189 rows x 93 columns]
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

C:\Users\Asus\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

ValueError: could not convert string to float: '2021-10-28'

In [ ]:
print(final_df)
print(final_df.columns)
print(final_df.dtypes)
cat = ["1m", "3m"]
print(final_df[cat].head(20))

In [ ]:
print(final_df["1m"].isna().sum())
print(final_df["3m"].isna().sum())

In [ ]:
# correlation calculation
feature_corr = final_df.copy().corr()

# sorting and using 1m
sortedDesc = feature_corr["1m"].sort_values(ascending=False) 
print(sortedDesc)

#cf_matrix = confusion_matrix(feature_corr)
plt.figure(figsize = (24,18))
sns.heatmap(feature_corr, annot=True, cbar=False, )

In [ ]:
# sorting and using 3m
sortedDesc = feature_corr["3m"].sort_values(ascending=False) 
print(sortedDesc)

#cf_matrix = confusion_matrix(feature_corr)
plt.figure(figsize = (24,18))
sns.heatmap(feature_corr, annot=True, cbar=False, )